# Generated by Django 4.1.2 on 2022-10-30 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_name', models.CharField(max_length=200)),
                ('ru_name', models.CharField(blank=True, max_length=200, null=True)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('post_view', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='backgroundImage/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForAreas/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForArt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForRelax/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForCafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForCafe/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForHotel/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForMasjid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForMasjid/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForNews/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForPhotos/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForRelax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForRelax/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForShrines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForShrines/')),
            ],
        ),
        migrations.CreateModel(
            name='NavbarName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uz_name', models.CharField(max_length=200)),
                ('ru_name', models.CharField(blank=True, max_length=200, null=True)),
                ('en_name', models.CharField(blank=True, max_length=200, null=True)),
                ('navbar_img', models.ImageField(blank=True, null=True, upload_to='navbarname/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_img', models.ImageField(upload_to='posts/')),
                ('uz_title', models.CharField(max_length=200)),
                ('ru_title', models.CharField(blank=True, max_length=200, null=True)),
                ('en_title', models.CharField(blank=True, max_length=200, null=True)),
                ('uz_description', models.CharField(max_length=100)),
                ('ru_description', models.CharField(blank=True, max_length=200, null=True)),
                ('en_description', models.CharField(blank=True, max_length=200, null=True)),
                ('uz_post', models.TextField()),
                ('ru_post', models.TextField(blank=True, null=True)),
                ('en_post', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('post_view', models.IntegerField(blank=True, default=0, null=True)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('navbar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.navbarname')),
            ],
        ),
        migrations.CreateModel(
            name='Hududlar',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
            ],
            bases=('main.post',),
        ),
        migrations.CreateModel(
            name='NavbarItems',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('navbar_img', models.ImageField(blank=True, null=True, upload_to='navbaritems/')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbarname')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='PhotoArxiv',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('photo', models.ImageField(upload_to='photo_arxiv/')),
            ],
            bases=('main.autodate',),
        ),
        migrations.CreateModel(
            name='WebSiteName',
            fields=[
                ('autodate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.autodate')),
                ('logo', models.ImageField(default='default/logo.png', upload_to='logo/')),
            ],
            bases=('main.autodate',),
        ),
        migrations.AddField(
            model_name='post',
            name='navbaritem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.navbaritems'),
        ),
    ]
