# Generated by Django 4.1.2 on 2022-10-31 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_news'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BackgroundImageForAreas',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForArt',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForCafe',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForHotel',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForMasjid',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForNews',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForPhotos',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForRelax',
        ),
        migrations.DeleteModel(
            name='BackgroundImageForShrines',
        ),
    ]
