# Generated by Django 4.1.2 on 2022-10-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_backgroundimageforareas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundImageForAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForAreas/')),
            ],
        ),
        migrations.CreateModel(
            name='BackgroundImageForNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bg_img', models.ImageField(upload_to='BackgroundImageForNews/')),
            ],
        ),
    ]
