# Generated by Django 4.1.2 on 2022-10-31 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_backgroundimageforareas_backgroundimagefornews'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderSlider',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.post')),
            ],
            bases=('main.post',),
        ),
    ]
