# Generated by Django 4.1.2 on 2022-11-01 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_headerslider'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foster', models.ImageField(upload_to='video_fosters/')),
                ('video', models.FileField(upload_to='videos/')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
