# Generated by Django 4.1.2 on 2022-11-02 13:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_videoarxiv'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoarxiv',
            name='title',
            field=models.CharField(default=datetime.datetime(2022, 11, 2, 13, 4, 49, 604502, tzinfo=datetime.timezone.utc), max_length=300),
            preserve_default=False,
        ),
    ]
