# Generated by Django 4.1.2 on 2022-11-02 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_photoarxiv_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoarxiv',
            name='title',
        ),
    ]
