# Generated by Django 4.1.2 on 2022-11-04 05:44

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_remove_photoarxiv_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uz_post',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
