# Generated by Django 4.1.2 on 2022-11-04 06:40

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_post_uz_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='en_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='ru_post',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
