# Generated by Django 4.1.2 on 2022-11-04 07:17

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_post_uz_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='uz_post',
            field=tinymce.models.HTMLField(),
        ),
    ]
