# Generated by Django 4.1.2 on 2022-11-06 04:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_post_en_post_alter_post_ru_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PhotoArxiv',
        ),
    ]
