# Generated by Django 4.1.2 on 2022-11-06 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_photoarxiv'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoArxiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photos', models.ImageField(upload_to='photoArxiv/')),
                ('add_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
