# Generated by Django 4.1.2 on 2022-11-06 07:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_photoarxiv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoarxiv',
            name='photos',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='photoArxiv/'),
        ),
    ]
