# Generated by Django 4.1.2 on 2022-11-06 10:10

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_photoarxiv_photos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundimage',
            name='bg_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='backgroundImage/'),
        ),
        migrations.AlterField(
            model_name='backgroundimageforareas',
            name='bg_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='BackgroundImageForAreas/'),
        ),
        migrations.AlterField(
            model_name='backgroundimagefornews',
            name='bg_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='BackgroundImageForNews/'),
        ),
        migrations.AlterField(
            model_name='navbaritems',
            name='navbar_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='navbaritems/'),
        ),
        migrations.AlterField(
            model_name='navbarname',
            name='navbar_img',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='navbarname/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_img',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='posts/'),
        ),
        migrations.AlterField(
            model_name='videoarxiv',
            name='foster',
            field=django_resized.forms.ResizedImageField(crop=None, force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='video_fosters/'),
        ),
        migrations.AlterField(
            model_name='websitename',
            name='logo',
            field=django_resized.forms.ResizedImageField(crop=None, default='default/logo.png', force_format='JPEG', keep_meta=True, quality=75, scale=0.5, size=[1920, 1080], upload_to='logo/'),
        ),
    ]
